### ISSUE TITLE
Build 3d model

### ISSUE THREAD

**Issue by LukasMosser** [zsylvester/meanderpy#1]
Running meanderby example notebook fails at the following on python 3:

```
ValueError                                Traceback (most recent call last)
<ipython-input-17-1cd93eb068e1> in <module>()
----> 1 chb_3d = chb.build_3d_model('submarine',h_mud=1.0,levee_width=3000.0,h=10.0,w=W,bth=10.0,dcr=10.0,dx=20.0,delta_s=deltas,starttime=chb.cl_times[50],endtime=chb.cl_times[55])

/content/meanderpy/meanderpy/_meanderpy.py in build_3d_model(self, model_type, h_mud, levee_width, h, w, bth, dcr, dx, delta_s, starttime, endtime)
    346         for i in range(0,2):
    347             pt = np.asarray(plt.ginput(1))
--> 348             pts[i,:] = pt
    349             plt.scatter(pt[0][0],pt[0][1])
    350         plt.plot([pts[0,0],pts[1,0],pts[1,0],pts[0,0],pts[0,0]],[pts[0,1],pts[0,1],pts[1,1],pts[1,1],pts[0,1]],'r')

ValueError: could not broadcast input array from shape (0) into shape (2)
```

**Comment by grongier** [comment]
Same issue here, seems like there's something wrong with plt.ginput and the Qt backend to open the window and do the clicking.

Calling `%matplotlib qt` before the imports in the first cell seems to do the trick (I also removed the call to `reload` in the initialization cell and the imports after run simulation), but then all the figures pop up in a Qt window instead of inline. 

This works for me to keep the non-interactive figures inline:
```
# Imports
%matplotlib inline
# Input parameters
# Initialize model
# Run simulation
%matplotlib qt
# Build 3D model
%matplotlib inline
# 3D model plots
```

**Comment by zsylvester** [comment]
I have not provided (until now) any description of how the 3D model building works. The default approach is that you have to click the upper left and lower right corners of the rectangular domain that you want to use for the 3D model. This only works if the plot is *not* inline, so yes, you need to run '%matplotlib qt' before running the cell for the 3D model. I have updated both the Jupyter notebook and the Readme file; hopefully this information is enough to get a 3D model going -- but let me know if that is not the case.

**Comment by LukasMosser** [comment]
I've managed to get as far as well in the meantime. I did run into an issue trying to click in the domain twice and then the code breaking, but have yet to investiagte more what could be the reason.

**Comment by KirillSimonov** [comment]
Dear @zsylvester ,
I followed your instruction and ran '%matplotlib qt' before running the cell for the 3D model and have image of model, but not able to click to choose the corners or rectangle. What do I need to do to click and after choosing correct rectangle, what do I need to do?
Thank you.

**Comment by zsylvester** [comment]
I have now updated the jupyter notebook with an example that illustrates 3D model building without having to define the x- and y-extent interactively.
