### ISSUE TITLE
An error when using "migrate" method

### ISSUE THREAD

**Issue by gantian127** [zsylvester/meanderpy#3]
Hello, 

I got an error when using meanderpy module. I used python 3.6, meanderpy v0.1.6, and numpy v1.18.4.

It seems to have a bug at line 487 when it is trying to get an integer value but instead got a float (1+s[-1]/deltas). A single slash is deprecated to do floor division under python 3. 

I tried to change the code as unew = np.linspace(0,1,1+int(s[-1])//int(deltas)) or unew = np.linspace(0,1,1+int(s[-1]/deltas))and it seems to work. If this is the right way to solve the problem, I can create a pull request for bug fix. Thank you!

<img width="660" alt="image" src="https://user-images.githubusercontent.com/5016511/86499315-cabe0580-bd47-11ea-9ebf-ff85c7469fd7.png">

**Comment by zsylvester** [comment]
Hi @gantian127 - yes, this is a Python 3 vs Python 2 issue. It is actually fixed in the development version, I just haven't updated yet the pip version.

**Comment by gantian127** [comment]
@zsylvester Good to know it has been fixed. Thank you!

**Comment by zsylvester** [comment]
Latest Pypi version now includes the fix.
